name: Build and Publish Docker Image

# refer to https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml 

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # <repo>
  REPO_NAME: powernukkitx


jobs:
  build-server:
    name: 构建PNX服务端
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: PowerNukkitX/PowerNukkitX
          submodules: true

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn -B package -DskipTests=false -Darguments="-Dmaven.javadoc.skip=true"

      - name: Rename artifacts
        run: |
          mv target/powernukkitx-*-SNAPSHOT.jar target/powernukkitx.jar
          mv target/powernukkitx-*-SNAPSHOT-shaded.jar target/powernukkitx-full.jar

      - name: Archive PNX Core
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: PowerNukkitX-Core
          path: target/powernukkitx.jar

      - name: Archive PNX Full
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: PowerNukkitX-Full
          path: target/powernukkitx-full.jar

      - name: Archive Libraries
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: PowerNukkitX-Libs
          path: target/libs/



  build-docker-image:
    needs: [build-server]
    name: 构建Docker镜像
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_HUB_USER }}/${{ env.REPO_NAME }}
          
      - name: Download Server Jar
        uses: actions/download-artifact@v3
        with:
            name: PowerNukkitX-Full

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
